config/routes.rb
Rails.application.routes.draw do
  
  resources :pins

  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "contact_us" => "pages#contact_us"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact_us
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all
  end

  def show
  end


  def new
    @pin = Pin.new
  end

  def edit
  end

 
  def create
    @pin = Pin.new(pin_params)


      if @pin.save
        redirect_to @pin, notice: 'Pin was successfully created.'
      else
        render :new
      end

  end

  def update
      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Pin was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @pin.destroy
      redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end

  private
    
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Medicine in Food", root_path, class: "navbar-brand" %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to "Home", root_path %></li>
        <li><%=link_to "About", about_path %></li>
        <li><%=link_to "Contact us", contact_us_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%=link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
           <li><%=link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/_secondheader.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Nutrition 101</a></li>

        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"> Nutrition programs for your health <span class="caret"></span></a>
	        <ul class="dropdown-menu" role="menu">
	            <li class="dropdown-submenu">
			        <a href="#">Health Conditions</a>
			        	<ul class="dropdown-submenu">
			        		<li><a href="#"> Hypothyroid</a></li>
			        		<li><a href="#"> Crohn's disease</a></li>
			        	</ul>
			        <a href="#">Recipes</a>
			    </li>
	         </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Unlock your personal dietitian <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Submit your blood test results</a></li>
            <li><a href="#">Meal plans for you</a></li>
            <li><a href="#">Diarise your meal intake to track progress</a></li>
          </ul>
        </li>
        <li class="active"><a href="#">Health articles</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medicine in Food</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<%= render 'layouts/secondheader' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info")%>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron left">
	<h3><strong> About us </strong></h3>
	<p> We are building a very exciting application </p>
</div>

app/views/pages/contact_us.html.erb
<div class="jumbotron left">
	<h3> <strong> We welcome feedback, comments and suggestions </strong> </h3>
	<p> Let us know so we can improve: medicineinfood@gmail.com </p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center", "page-header">
	<h1>Medicine in Food 
		<small>Discover food cures for your health conditions</small></h1>
	<% if user_signed_in? %>
		#do something
	<% else %>
		<p> 
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %> 
		</p>
</div>
<div class="jumbotron left">
	<h2>1. Understand the power of nutrition for your health</h2>
	<p> Understand the benefit of nutrition for your body    <%= link_to "Free e-book", "#", class: "btn btn-primary btn-lg" %>
	</p>
</div>
<div class="jumbotron left">
	<h2>2. Nutrition programs for your health</h2>
	<p>Search by health conditions   <%= link_to "Health conditions", "#", class: "btn btn-primary btn-lg" %> 
	</p>
	<p>Cook from our recipes collection to become better   <%= link_to "Browse recipes", "#", class: "btn btn-primary btn-lg" %>
	</p>
</div>
<div class="jumbotron left">
	<h2>3. Unlock your personal dietitian</h2>
	<p>Receive a personalised meal plans to follow based on your health conditions and tools to track improvements   <%= link_to "Take me to my meal plan", "#", class: "btn btn-primary btn-lg" %>
	</p>
	<% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="actions", "form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Editing pin</h1>
	</div>

	<div class="panel-body", "form-control">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Show', @pin %> |
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>Our recipes collection</h1>
  </div>
  <div class="panel-heading">
    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @pins.each do |pin| %>
          <tr>
            <td><%= pin.description %></td>
            <td><%= link_to 'Show', pin %></td>
            <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
            <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
  </div>
  <div class="panel-footer">
  <%= link_to 'New Pin', new_pin_path, class: "btn btn-primary"%>
  </div>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>New pin</h1>
	</div>

	<div class="panel-body", "form-control">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>